#!/bin/bash
set -e

SCHEDULER_SCRIPT="backup-scheduler"
CONFIG_DIR="/etc/ldap-backup"
CONFIG="$CONFIG_DIR/_schedule.cfg"

case "$1" in
    remove|deconfigure)
        # Remove /etc/ldap-backup directory if it is empty
        if [ -d "$CONFIG_DIR" ] && [ -z "$(command ls -A "$CONFIG_DIR")" ]; then
          rmdir "$CONFIG_DIR"
        else
          echo "Notice: The directory $CONFIG_DIR is not empty. It will not be deleted."
        fi

        # Remove the cronjob from the current user's crontab
        (crontab -l | grep -v "$CONFIG # LDAP backup" ) | crontab -

        ;;
    *)
        # Do nothing on other actions
        exit 0
        ;;
esac

# Continue with package removal
exit 0
