name: Merge master into develop

env:
  GIT_COMMITTER_EMAIL: bot@srnjak.com
  GIT_COMMITTER_NAME: Srnjak bot

on:
  workflow_dispatch:
  workflow_run:
    workflows: [ "Release workflow" ]
    types:
      - completed

jobs:
  merge:
    runs-on: ubuntu-latest
    if: >
      github.event.workflow_run.conclusion == 'success'
          || github.event.workflow_dispatch
    steps:
      - name: Set up Git identity
        run: |
          git config --global user.email "${{ env.GIT_COMMITTER_EMAIL }}"
          git config --global user.name "${{ env.GIT_COMMITTER_NAME }}"

      - name: Checkout code
        uses: actions/checkout@v3
        with:
          ref: develop
          fetch-depth: 0
      - run: git config --global --add safe.directory "$GITHUB_WORKSPACE"

      - name: Merge master into develop
        run: |
          git merge --no-ff --no-edit origin/master
          git push origin develop
        env:
          GITHUB_TOKEN: ${{ secrets.BOT_TOKEN }}
